class LookImage {
    constructor(src, isClasse, hasModal = false, modalText = "") {
      this.src = src;
      this.isClasse = isClasse; // true = classe, false = pas classe
      this.hasModal = hasModal;
      this.modalText = modalText;
    }
  }
  
  const allImages = [
    new LookImage("image1.jpg", true, true, "Vous fuyez l’art sartorial et le vestiaire classique parce que « trop cher » et « trop bourgeois ». Pourtant, claquer 180 € dans des Nike Air Max TN et un ensemble assorti, ça ne vous dérange pas. Drôle d’économie : aujourd’hui, s’habiller « prolo » coûte plus cher qu’un costume correct. Et étrangement, vous ne mettez jamais les pieds chez Kiabi ou Gémo… Donc non, ce n’est pas une question de prix. C’est l’élégance que vous fuyez, le bon goût que vous détestez."),
    new LookImage("image2.jpg", false, true, "Ne prenez surtout pas exemple sur les rappeurs : ils sont à fuir. Cela fait belle lurette que le rap n’a plus rien de « populaire ». Quoi, vous tombez des nues ? Vous voyez beaucoup de rappeurs s’employer à rendre la vie des gens plus juste, plus consciente des problèmes de société, ou à dénoncer les dérives politiques ? Que nenni ! Leur « engagement » se résume à glorifier la drogue, les drive-by et à s’exhiber dans des tenues ostentatoires de piètre qualité. Résultat : les gogos achètent, et les plus pauvres s’endettent pour les imiter avec leurs maigres économies. Voilà la grande contribution du rap actuel : une foire à la vanité et au toc."),
    new LookImage("image3.jpg", true, true, "Consommer moins mais mieux, avec un impact moindre sur la planète : voilà l’ADN du sartorialisme. Un pantalon, un costume, un manteau chez un tailleur, c’est un vêtement unique, à sa taille, en matériaux nobles et propres, avec en prime un bilan carbone réduit. Exactement ce que la fast fashion ne produira jamais. Oui, c’est plus cher. Mais quand on y pense, l’art sartorial trace la voie d’une économie vestimentaire éthique. Encore faudrait-il que la masse soit éduquée à la décroissance, à l’élégance et au bon goût. Autant dire que ce n’est pas gagné."),
    new LookImage("image4.JPG", false, true, "« Le sartorialisme, c’est pour les bourgeois. » Voilà le cri de guerre préféré de ceux qui n’ont tout simplement pas envie de s’habiller décemment. Ces champions de l’authenticité auto-proclamée sont capables de se pointer en jean élimé à un mariage, persuadés que leur laisser-aller est une forme de rébellion et d'expression de soi. Résultat : une garde-robe aussi fade et triste qu’un Happy Meal oublié au soleil.Il fut un temps – pas si lointain – où même l’ouvrier arborait fièrement son trois-pièces du dimanche via un tailleur local. Pas de fast fashion, pas de montagnes de haillons expédiés par conteneurs en Afrique. Aujourd’hui, par contre, la paresse se déguise en discours politique : « Je refuse d’être élégant parce que je n’aime pas les bourgeois ». Traduction : « Je préfère ressembler à rien plutôt que d’assumer un minimum de goût. »"),
    new LookImage("image5.jpg", true, true, "Pour les irréductibles casual incapables d’entrer dans l’univers sartorial, des cravates et des revers italiens, il existe une alternative : le style preppy, Ivy League et toutes ses déclinaisons intemporelles. Donc plus d’excuses. Lâchez vos guiboles de rappeurs, vos hoodies de dealers, vos jeans H&M qui se déchirent à l’entrejambe en deux mois. Cessez de suivre les trends crétins des « influenchieurs », d’acheter compulsivement après un épisode de téléréalité sans queue ni tête. Et surtout, arrêtez d’écouter des rappeurs intoxiqués à la lean ou au shit coupé à l’huile de moteur qui vous vendent des mensonges stylistiques. Rejoignez enfin le camp des intemporels."),
    new LookImage("image6.jpg", true, true, "L’art sartorial et la passion du vestiaire classique n’ont rien à voir avec les pulsions consuméristes textiles. Ici, la qualité, l’histoire et le style priment sur les tendances fugaces et la frénésie d’achats compulsifs dictés par les influenchieurs. De plus, choisir avec discernement, c’est soutenir le local, l’artisanat, et par extension, une démarche écologique. Car oui : l’industrie textile pollue massivement. La production de masse détruit, uniformise, et abrutit.Alors, bien sûr, les « non mais… » viendront objecter : « Ça crée des emplois dans les pays défavorisés ». Ah, formidable ! Quel beau progrès : sacrifier des générations d’esclaves modernes pour produire à bas coût des tissus médiocres remplies de plastique, que vous jetterez aussitôt pour les brader sur Vinted et faire peter le carbone transport. Changer ses comportements d’achat n’est pas qu’une question de morale : c’est un véritable travail sur soi. Mais ça, c’est évidemment plus fatigant que de cliquer sur « ajouter au panier »"),
    new LookImage("image7.jpg", false, true, "Voici Lapo Elkann : riche, très riche… mais sapé comme une bip...... Parfait exemple de millionaire incapable d’investir correctement ses deniers dans un minimum d’allure. Comme quoi, l’élégance n’a rien à voir avec la taille du compte en banque, mais tout avec la culture esthétique. Alors surtout, n’allez pas demander conseil à Jeff Bezos, Elon Musk ou Mark Zuckerberg pour vous habiller avec goût : leur talent s’arrête au portefeuille. Pour apprendre l’élégance, mieux vaut observer ces anonymes qui, sans fortune colossale, maîtrisent l’art de bien se vêtir"),
    new LookImage("image8.jpg", true,true , " Il fut une époque où la société anglaise changeait de tenue cinq fois par jour : rendez-vous professionnels, déjeuners, tea time, dîners, mondanités nocturnes… Épuisant, peut-être, mais chaque moment avait sa tenue, son importance. Aujourd’hui ? Capuche, jean, basket matin, midi, soir. Capuche au resto, capuche au boulot, capuche en famille. Capuche all day, every day.On nous vend ça comme « cool », « authentique », « humble ». Bien sûr… on y croit."),
    new LookImage("image9.JPG", false, true, "La vie est faite de moments : matin, boulot, déjeuner, week-end, mariages, dîners, rendez-vous pro, restos chics… Chaque occasion a sa tenue. Enfin, en théorie. Parce que pour certains, c’est hoodie matin, midi et soir. Au travail, chez la belle-famille, même dans un resto chic : aucune nuance, aucune différence. Tristesse absolue.Alors oui, chacun fait ce qu’il veut… mais derrière ce « chacun fait ce qu’il veut », il y a surtout une majorité qui a choisi le style m’en-foutiste. McDonald’s disait jadis « Venez comme vous êtes » ; beaucoup l’ont pris au pied de la lettre, au point de se pointer en jogging le jour de leur entretien d’embauche. Paresse érigée en art de vivre."),
    new LookImage("image10.jpg", true),
    new LookImage("image12.jpeg", true),
    new LookImage("image13.png", true),
    new LookImage("image14.jpg", true),
    new LookImage("image15.jpg", true, true, "Rien de pire que celui qui confond le banquier coincé dans un costume Zara de pacotille par obligation professionnelle avec l’esthète en quête de sprezzatura. Totalement différent. Quelle pauvreté de nuance, quel manque d’ouverture d’esprit ! Le sartorialisme, c’est plonger dans l’histoire, maîtriser l’artisanat, connaître les codes du passé pour les réinterpréter aujourd’hui.Idem pour ceux qui osent comparer un politicien fade de l’Assemblée nationale, coincé dans un costume banal fabriqué par un tailleur qui s’en moque, avec un aficionado qui traîne tous les deux mois à Savile Row et Jermyn Street."),
    new LookImage("image16.jpg", true, true, "« Le"),
    new LookImage("image17.jpg", false),
    new LookImage("image18.jpg", true, true, "On saire ?"),
    new LookImage("image19.jpg", false),
    new LookImage("image20.jpg", true, true, " On ue"),
    new LookImage("image21.jpg", true),
    new LookImage("image22.jpg", false, true, "se la raconte trop"),
    new LookImage("image23.jpg", true),
    new LookImage("image24.JPG", false),
    new LookImage("image25.jpg", false),
    new LookImage("image26.jpg", true),
    new LookImage("image27.jpg", false),
    new LookImage("image28.jpg", true),
    new LookImage("image29.jpg", true),
    new LookImage("image30.jpg", true),
    new LookImage("image31.jpg", false),
    new LookImage("image32.jpg", true),
    new LookImage("image33.jpg", true),
    new LookImage("image34.jpg", true),
    new LookImage("image35.jpg", true),
    new LookImage("image36.jpg", true),
    new LookImage("image37.jpg", false),
    new LookImage("image38.jpg", true),
    new LookImage("image39.jpg", true),
    new LookImage("image40.JPG", false),
    new LookImage("image41.jpg", false),
    new LookImage("image42.JPG", false), 
    new LookImage("image43.jpg", true),
    new LookImage("image44.jpg", false),
    new LookImage("image45.JPG", false),
    new LookImage("image46.jpg", true),
    new LookImage("image47.jpg", true),
    new LookImage("image48.jpg", true),
    new LookImage("image49.jpg", true),
    new LookImage("image50.JPG", false),
    new LookImage("image51.jpg", true),
    new LookImage("image52.jpg", true),
    new LookImage("image53.jpg", true),
    new LookImage("image54.jpg", true),
    new LookImage("image55.jpg", true),
    new LookImage("image56.jpg", true),
    new LookImage("image57.jpg", true),
    new LookImage("image58.jpg", true),
    new LookImage("image59.jpg", true),
    new LookImage("image60.jpg", true),
    new LookImage("image61.jpg", true),
    new LookImage("image62.jpg", true),
    new LookImage("image63.jpg", true),
    new LookImage("image64.JPG", false),
    new LookImage("image65.jpg", false),
    new LookImage("image66.jpg", false),
    new LookImage("image67.jpg", false),
    new LookImage("image68.jpg", false),
    new LookImage("image69.jpg", false),
    new LookImage("image70.jpg", true),
    new LookImage("image71.jpg", true),
    new LookImage("image72.jpg", false),
    new LookImage("image73.jpg", false),
    new LookImage("image74.jpg", false),
    new LookImage("image75.jpg", false),
    new LookImage("image76.jpg", true),
    new LookImage("image77.jpg", true),
    new LookImage("image78.jpg", true),
    new LookImage("image79.jpg", true),
new LookImage("image80.jpg", true),
new LookImage("image81.jpg", true),
new LookImage("image82.jpg", true),  
new LookImage("image83.jpg", false),
new LookImage("image84.jpg", false),
new LookImage("image85.jpeg", true),
new LookImage("image86.jpeg", true),
new LookImage("image87.jpeg", true),
new LookImage("image88.jpg", true),
new LookImage("image89.jpg", false),
new LookImage("image90.jpg", false),
new LookImage("image91.jpg", true),
new LookImage("image92.jpg", false),
new LookImage("image93.jpg", false),
new LookImage("image94.jpg", false),
new LookImage("image95.jpg", false),
new LookImage("image96.jpg", true),
new LookImage("image97.jpg", true),
new LookImage("image98.jpg", true),
new LookImage("image99.jpg",true),
new LookImage("image100.jpg", true),
new LookImage("image101.jpg", true),
new LookImage("image102.jpg", false),
new LookImage("image103.jpg", true),
new LookImage("image104.jpg", true),
new LookImage("image105.jpg", false, true, "La mode est un moyen d'expression, c'est vrai. mais elle ne doit pas etre synonyme de n'importe quoi"),
new LookImage("image106.jpg", true, true, "Il peut arriver dans de rares occasions que le street wear puisse etre brillant...."),
new LookImage("image107.jpg", true),
new LookImage("image108.jpg", true),
new LookImage("image109.jpg", false),
new LookImage("image110.jpg", true),
new LookImage("image111.jpg", false),
new LookImage("image112.jpg", false),
new LookImage("image113.jpg", true),
new LookImage("image114.jpg", false, true, "Vous fuyez l’art sartorial et le vestiaire classique parce que « trop cher » et « trop bourgeois ». Pourtant, claquer 180 € dans des Nike Air Max TN et un ensemble assorti, ça ne vous dérange pas. Drôle d’économie : aujourd’hui, s’habiller « prolo » coûte plus cher qu’un costume correct. Et étrangement, vous ne mettez jamais les pieds chez Kiabi ou Gémo… Donc non, ce n’est pas une question de prix. C’est l’élégance que vous fuyez, le bon goût que vous détestez."),
new LookImage("image115.jpg", false),
new LookImage("image116.jpg", true),
new LookImage("image117.jpg", true),
new LookImage("image118.jpg", true),
new LookImage("image119.jpg", true),
new LookImage("image120.jpg", true),
new LookImage("image121.jpg", true),
new LookImage("image122.jpg", true),
   
];
  
  // Fonction pour obtenir 10 images aléatoires uniques
  function getRandomImages() {
    const shuffled = [...allImages].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, 10);
  }
  
  let selectedImages = []; // Pour la session en cours