class LookImage {
    constructor(src, isClasse, hasModal = false, modalText = "") {
      this.src = src;
      this.isClasse = isClasse; // true = classe, false = pas classe
      this.hasModal = hasModal;
      this.modalText = modalText;
    }
  }
  
  const allImages = [
    new LookImage("image1.jpg", true, true, "Ne vous attendez jamais à entendre les partis dits verts faire l’éloge d’une écologie de la consommation éclairée, fondée sur le discernement, la durabilité et le goût du beau. Jamais il ne leur viendrait à l’esprit de promouvoir l’acquisition de vêtements confectionnés proprement, ni d’encourager à franchir la porte d’un tailleur pour soutenir une industrie locale exigeante et peu polluante"),
    new LookImage("image2.jpg", false, true, "Il est devenu de bon ton, n'est-ce pas, de clamer haut et fort qu'il faut sauver la planète, secourir une jeunesse apparemment perdue et réformer nos habitudes de consommation ! Mais pourquoi, alors, ne pas proposer une vraie solution ? Pourquoi ne pas inculquer et promouvoir l’art sartorial, ce savoir-faire vestimentaire classique, dans nos sociétés occidentales ? L'art du vêtement qui ne se contente pas de flatter l'éphémère, mais qui privilégie les matières nobles et durables, soutient les petites mains locales et fait renaître l'artisanat dans sa forme la plus pure et la plus exquise.Voilà, sans doute, une alternative à la catastrophe qu’est la fast fashion"),
    new LookImage("image3.jpg", true, true, "Soyons honnêtes, ne jouons pas les hypocrites au revers trop sage : il est une forme d’obsession qui naît inévitablement lorsqu’on pénètre dans les arcanes du sartorialisme. Une douce pathologie, une passion textile qui confine au mysticisme, une quête de l’absolu camouflée sous les oripeaux d’un blazer à rayures tennis.Cela commence souvent par une épaule napolitaine, se poursuit avec un revers généreux, et finit en apothéose dans une salle obscure de Biella, où l’on imagine, dans une semi-hallucination, des maîtres tailleurs possédés, maniant la craie et le ciseau comme des poètes forcenés."),
    new LookImage("image4.JPG", false, true, "En 2021, pas moins de 900 millions de vêtements usagés ont été gracieusement expédiés au Kenya. Une aumône textile, une générosité post-consommation des pays riches. Sauf que, petit détail : un tiers de ces pièces était si atrocement conçu — bourré de plastique, de médiocrité et de sueur d’enfant — qu’il a été directement brûlé ou jeté, polluant joyeusement les sols et les poumons des habitants. Le summum de l’élégance occidentale : offrir son rebut à l’Afrique, tout en dégazant un nuage toxique pour la planète. Chapeau bas. Et l’on s’étonne ensuite que certains pestent contre la fast fashion ?"),
    new LookImage("image5.jpg", true, true, "Le style Ivy League et sartorial a une dimension historique et culturelle forte, inspirée des universités prestigieuses, du tailoring britannique et de la dolce vita italienne Le streetwear, bien que culturellement intéressant (hip-hop, skate, basketball), repose davantage sur la tendance et l’image commerciale"),
    new LookImage("image6.jpg", true, true, "Beaucoup de personnes rejettent l'art sartorial car ils partent du principe que l'art vestimentaire formalise tout. Ce qui en soit n'est pas faux. Cela dit le formalisme permet de poser un cadre c'est la que la creativité donne le meilleur d'elle meme. Sans cadre la creativité se laisse aller au grand n'importe quoi. Jouer avec les regles plus ou moins contraignantes du costume masculin est un art subtil dans lequel les esprits exigeants mais joueur s'adonnent à coeur joie"),
    new LookImage("image7.jpg", false, true, "lapo elkann toujours aussi naze"),
    new LookImage("image8.jpg", true,true , "Soyons honnêtes : les règles vestimentaires qui gouvernaient la vie d’un gentleman au XXe siècle tenaient plus de l’ascèse que du caprice. Il fallait parfois changer de tenue cinq fois par jour – oui, cinq – en fonction de l’heure, de l’activité, du lieu, voire de l’humeur du majordome. C’était un ballet textile d’une rigueur presque militaire. On passait de la tenue de promenade à celle du déjeuner, puis du tea-time à celle du dîner formel, sans oublier le smoking de rigueur pour la soirée. Qui fait encore ça aujourd’hui ? Même le cadre sup le plus dopé au personal branding n’oserait rivaliser. Quant aux nobles de notre époque,  il est à craindre qu’eux aussi aient troqué le vestiaire patrimonial pour un jean Uniqlo et un pull en cachemire fatigué. Triste époque où même les héritiers manquent d’héritage.il faut le reconnaître : ces anciens codes étaient exigeants, contraignants, et parfois franchement absurdes… mais quelle dramaturgie de l’existence ! Derrière chaque changement de tenue, il y avait un art de vivre, une liturgie du quotidien. Ces hommes, loin d’être de simples vêtements sur pattes, célébraient chaque moment comme une scène de théâtre. Le déjeuner n’était pas un repas rapide, mais un rituel. Une promenade n’était pas une pause santé, mais une apparition.Aujourd’hui ? C’est le règne du jean-basket omniprésent, cet uniforme sans âme porté de 7h à 23h, du lit au bar en passant par le bureau. Une tenue unique pour une vie qui ne distingue plus rien : ni le lieu, ni l’heure, ni la compagnie."),
    new LookImage("image9.JPG", false, true, "La fast fashion s’adapte rapidement aux tendances, permettant aux consommateurs de renouveler leur garde-robe en fonction de leurs goûts changeants Le sartorialisme reste associé à un certain formalisme, tandis que le streetwear et la fast fashion s’adaptent à une société en perpétuel mouvement"),
    new LookImage("image10.jpg", true),
    new LookImage("image12.jpeg", true),
    new LookImage("image13.png", true),
    new LookImage("image14.jpg", true),
    new LookImage("image15.jpg", true, true, "Avez-vous remarqué, chers amis, à quel point les Parisiens semblent étrangers dans leur propre ville ? Non pas étrangers par passeport, mais par culture, par allure, par attitude. Ce ne sont plus des citadins, ce sont des intrus dans un décor trop grand pour eux. Il y a quelque chose d’obscène à voir ces silhouettes négligées errer entre les colonnades haussmanniennes comme des figurants mal castés dans un chef-d’œuvre classique. Regardez-les : hoodies informes, baskets sales, jogging fluo — et parfois, comble du tragique, une casquette vissée sur un chignon néo-féministe. Et tout cela au pied d’un immeuble où, jadis, un notaire frottait ses gants en peau de chevreau en sortant d’une berline tirée par deux chevaux. Ce n’est plus un décalage, c’est une rupture esthétique. Un viol de l’harmonie. Et comme si cela ne suffisait pas, nous avons atteint ce degré terminal de confusion mentale où l’on peut affirmer sans ciller qu’un homme peut tomber enceint, pendant que le Panthéon contemple la scène en silence, peut-être déjà résigné à son sort. Soyons clairs : Paris souffre. Paris est en dysphorie. Son architecture ne reconnaît plus ses habitants. La ville réclame une thérapie de choc. Il ne s’agit plus simplement de repeindre les façades ou de réparer les pavés — il faut soigner l’âme textile de la capitale. Il faut que les Parisiens s’habillent enfin à la hauteur de leur décor. La ville appelle la flanelle, le tweed, la chemise à col cassé, les souliers en cuir noble. Pas le nylon, le plastique, le jogging gris souris.Je vous entends déjà, dans un gémissement mou, me rappeler que l’habit ne fait pas le moine. Quelle sottise. C’est justement parce que l’époque n’a plus de moines qu’elle n’a plus d’habits. Aujourd’hui, s’habiller est un acte politique. Votre tenue trahit tout : vos névroses, vos idéaux, votre vote, votre place dans la chaîne alimentaire culturelle. Et croyez bien que si les hommes politiques s’entourent de conseillers en image, ce n’est pas pour le plaisir de jouer à la poupée.On ne peut pas laisser cohabiter la beauté architecturale de Paris — ce qu’il en reste — avec la laideur militante de ceux qui la piétinent en Balenciaga sales."),
    new LookImage("image16.jpg", true, true, "« Le sartorialisme ? Tous des clones en costume, bons à bosser pour le Grand Capital à La Défense. »Cette phrase, vous l’avez sans doute déjà entendue, beuglée entre deux slurps de bubble tea ou tapée rageusement sur Twitter entre deux relectures d’un thread indigent sur la décroissance. Elle suinte l’amalgame paresseux et le jugement low-cost.Car oui, confondre un cadre dynamique engoncé dans un costume Zara en polyester, acheté à la hâte le dimanche au centre commercial pour le fameux “entretien du lundi”, avec un véritable esthète du vestiaire classique, c’est comme confondre une bière tiède avec un grand cru classé. C’est infâme. Mais cela dit beaucoup de notre époque : la nuance y est morte, écrasée entre deux slogans et trois emojis. Tout est manichéen, binaire, idiot. La politique ? Un sketch de marionnettes : les gentils seraient à gauche, les méchants à droite — ou l’inverse selon le serveur sur lequel vous vous connectez. Il n’y a plus d’analyse, seulement des postures.Dans ce brouhaha idéologique, on en arrive donc à accuser le sartorialisme d’uniformisation. Ah ! Comme si le blazer croisé en laine froide de Vitale Barberis Canònico avait quelque chose à voir avec le hoodie H&M floqué de caractères japonais au hasard"),
    new LookImage("image17.jpg", false),
    new LookImage("image18.jpg", true, true, "On s’habille pour s’elever. Ca peut paraître pompeux comme affirmation mais c’est vrai. Sinon on s’habille juste pour ne pas etre nu, et la ca laisse place a des derives… Vous avez envie de projeter quoi à travers votre vestiaire ?"),
    new LookImage("image19.jpg", false),
    new LookImage("image20.jpg", true, true, " On nous bassine avec l’obsolescence programmée de nos téléphones, de nos lave-vaisselles et de nos trottinettes connectées, comme si cette escroquerie industrielle ne concernait que les objets techniques. Quelle ingénuité ! S’il est un domaine où l’obsolescence est devenue un art – une religion même – c’est bien celui de la mode. Non pas la mode au sens noble du terme mais la mode contemporaine : cette farce renouvelée chaque trimestre, orchestrée par des gourous d’Instagram en jogging fluo et des magazines qui sentent le papier glacé et le cerveau vide.Ici, l’obsolescence ne vient pas d’une couture fragile ou d’un tissu bas de gamme cousu dans l’urgence à des milliers de kilomètres, dans des usines où la misère porte un badge. Non. L’obsolescence ici est morale, presque ontologique : elle se décrète depuis les bureaux d’un rédacteur de tendances ou la story d’un influenceur qui, à défaut de style, a beaucoup de followersAinsi, ce pull que vous aimiez hier est aujourd’hui « has been », cette veste que vous trouviez flatteuse est désormais « cringe », ce pantalon bien taillé est devenu « pas validé TikTok ». Le vêtement n’est plus jugé sur sa tenue, sa coupe, sa noblesse de matière, mais sur son degré d’obéissance à l’humeur volatile d’une époque qui confond la nouveauté avec la vérité."),
    new LookImage("image21.jpg", true),
    new LookImage("image22.jpg", false, true, "se la raconte trop"),
    new LookImage("image23.jpg", true),
    new LookImage("image24.JPG", false),
    new LookImage("image25.jpg", false),
    new LookImage("image26.jpg", true),
    new LookImage("image27.jpg", false),
    new LookImage("image28.jpg", true),
    new LookImage("image29.jpg", true),
    new LookImage("image30.jpg", true),
    new LookImage("image31.jpg", false),
    new LookImage("image32.jpg", true),
    new LookImage("image33.jpg", true),
    new LookImage("image34.jpg", true),
    new LookImage("image35.jpg", true),
    new LookImage("image36.jpg", true),
    new LookImage("image37.jpg", false),
    new LookImage("image38.jpg", true),
    new LookImage("image39.jpg", true),
    new LookImage("image40.JPG", false),
    new LookImage("image41.jpg", false),
    new LookImage("image42.JPG", false), 
    new LookImage("image43.jpg", true),
    new LookImage("image44.jpg", false,),
    new LookImage("image45.JPG", false),
    new LookImage("image46.jpg", true),
    new LookImage("image47.jpg", true),
    new LookImage("image48.jpg", true),
    new LookImage("image49.jpg", true),
    new LookImage("image50.JPG", false),
    new LookImage("image51.jpg", true),
    new LookImage("image52.jpg", true),
    new LookImage("image53.jpg", true),
    new LookImage("image54.jpg", true),
    new LookImage("image55.jpg", true),
    new LookImage("image56.jpg", true),
    new LookImage("image57.jpg", true),
    new LookImage("image58.jpg", true),
    new LookImage("image59.jpg", true),
    new LookImage("image60.jpg", true),
    new LookImage("image61.jpg", true),
    new LookImage("image62.jpg", true),
    new LookImage("image63.jpg", true),
    new LookImage("image64.JPG", false),
    new LookImage("image65.jpg", false),
    new LookImage("image66.jpg", false),
    new LookImage("image67.jpg", false),
    new LookImage("image68.jpg", false),
    new LookImage("image69.jpg", false),
    new LookImage("image70.jpg", true),
    new LookImage("image71.jpg", true),
    new LookImage("image72.jpg", false),
    new LookImage("image73.jpg", false),
    new LookImage("image74.jpg", false),
    new LookImage("image75.jpg", false),
    new LookImage("image76.jpg", true),
    new LookImage("image77.jpg", true),
    new LookImage("image78.jpg", true),
    new LookImage("image79.jpg", true),
new LookImage("image80.jpg", true),
new LookImage("image81.jpg", true),
new LookImage("image82.jpg", true),  
new LookImage("image83.jpg", false),
new LookImage("image84.jpg", false),
new LookImage("image85.jpeg", true),
new LookImage("image86.jpeg", true),
new LookImage("image87.jpeg", true),
new LookImage("image88.jpg", true),
new LookImage("image89.jpg", false),
new LookImage("image90.jpg", false),
new LookImage("image91.jpg", true),
new LookImage("image92.jpg", false),
new LookImage("image93.jpg", false),
new LookImage("image94.jpg", false),
new LookImage("image95.jpg", false),
new LookImage("image96.jpg", true),
new LookImage("image97.jpg", true),
new LookImage("image98.jpg", true),
new LookImage("image99.jpg", true),
new LookImage("image100.jpg", true),
new LookImage("image101.jpg", true),
new LookImage("image102.jpg",  false),
new LookImage("image103.jpg", true),
new LookImage("image104.jpg", true),
new LookImage("image105.jpg", false, true, "La mode est un moyen d'expression, c'est vrai. mais elle ne doit pas etre synonyme de n'importe quoi"),
new LookImage("image106.jpg", true, true, "Il peut arriver dans de rares occasions que le street wear puisse etre brillant...."),
new LookImage("image107.jpg", true),
new LookImage("image108.jpg", true),
new LookImage("image109.jpg", false),
new LookImage("image110.jpg", true),
new LookImage("image111.jpg", false),
new LookImage("image112.jpg", false),
new LookImage("image113.jpg", true),
new LookImage("image114.jpg", false),
new LookImage("image115.jpg", false),
new LookImage("image116.jpg", true),
new LookImage("image117.jpg", true),
new LookImage("image118.jpg", true),
new LookImage("image119.jpg", true),
new LookImage("image120.jpg", true),
new LookImage("image121.jpg", true),
new LookImage("image122.jpg", true),
   
];
  
  // Fonction pour obtenir 10 images aléatoires uniques
  function getRandomImages() {
    const shuffled = [...allImages].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, 10);
  }
  
  let selectedImages = []; // Pour la session en cours